HW 4.15
htmlacademy-javascript/853355-kekstagram-27 pull request #3
Opened 2022-10-14 21:39 UTC by Farkhadov95

2022-10-15 17:11 UTC, babtshe requested changes

2022-10-15 17:11 UTC, babtshe commented on js/main.js
> +  max: 25
Есть смысл указывать только верхнее ограничение. Маловероятно, что ID будет меньше нуля

2022-10-15 17:11 UTC, babtshe commented on js/main.js
> +function checkStringLength (input, maxLength) {
есть смысл переименовать функцию так, чтобы было понятно что она делает и возвращает. В данном случае можно именовать по схеме «is + признак», см пример в [критерии](https://up.htmlacademy.ru/javascript/27/criteries#b4)

2022-10-15 17:11 UTC, babtshe commented on js/main.js
> +  id: getRandomInt(ID_RANGE.min, ID_RANGE.max),
id комментария уникален, есть смысл придумать альтернативный способ генерации.

2022-10-15 17:11 UTC, babtshe commented on js/main.js
> +  name: getRandomArrayElement(USER_NAMES)
было бы правильно добавить единообразия в названия функций. В одном случае функция содержит get, в другом create, хотя обе возвращают значение.

2022-10-15 17:11 UTC, babtshe commented on js/main.js
> +  id: getRandomInt(PHOTO_RANGE.min, PHOTO_RANGE.max),
тут тоже нужны уникальные ID

2022-10-17 13:10 UTC, Farkhadov95 commented on js/main.js
> +  id: getRandomInt(ID_RANGE.min, ID_RANGE.max),
Уникальные не значит рандомные, да? Я пробовал создать рандомайзер уникальных ID в диапозоне 1-25 и проиграл)

2022-10-18 10:44 UTC, babtshe requested changes

2022-10-18 10:44 UTC, babtshe commented on js/main.js
> +// };
закомментированные куски кода не должны попадать в репозиторий

2022-10-18 10:44 UTC, babtshe commented on js/main.js
> +
Функция для выдачи уникальных идентификаторов не должна знать для кого этот идентификатор выдаётся. Если тебе нужно выдавать несколько идентификаторов по разным правилам, будет правильно делать для этого отдельные функции.
По сути только для фоток есть лимит в 25 штук, комментарии не попадают под подобные ограничения.

2022-10-18 10:46 UTC, babtshe commented on js/main.js
> +  id: getRandomInt(ID_RANGE.min, ID_RANGE.max),
Да, случайность тут совершенно не нужна, идентификаторы вполне могут по порядку идти. Но если вдруг захочешь сделать рандомайзер, достаточно просто перемешать массив ID случайным образом и идти по нему - данные будут случайные и уникальные.

2022-10-18 13:09 UTC, babtshe approved these changes

2022-10-18 13:09 UTC, merged