Module7 task2
htmlacademy-javascript/853355-kekstagram-27 pull request #6
Opened 2022-11-03 14:05 UTC by Farkhadov95

2022-11-05 14:01 UTC, babtshe requested changes
Хорошо бы поправить ошибку при закрытии попапа:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/30229773/200123572-5f0132f3-aa33-45a0-887a-f7757ebda25e.png">

Обрати внимание, падающие тесты гарантируют отправку домашки на доработку:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/30229773/200123618-6cb5fb01-b26f-411b-b4d1-926dc059647f.png">

2022-11-05 14:01 UTC, babtshe commented on js/popup.js
> +  comment.querySelector('.social__text').textContent = message;
можно же сразу подставить значения с помощью строковых литералов, например:
`` `string of text ${someVariable}` ``

2022-11-05 14:01 UTC, babtshe commented on js/popup.js
> +  pictureDialog.querySelector('.social__caption').textContent = description;
см [критерий](https://up.htmlacademy.ru/javascript/27/criteries#d21)

2022-11-05 14:01 UTC, babtshe commented on js/popup.js
> +    hidePopup();
❗️

2022-11-05 14:01 UTC, babtshe commented on js/popup.js
> +const showPopup = (data) => {
`data` - неудачное название переменной, так как не даёт никакой информации о содержимом.

2022-11-05 17:18 UTC, Farkhadov95 commented on js/popup.js
> +    hidePopup();
а что можно сделать с этой функцией? У меня тут две функции которые вызывают друг друга. Если поменять местами, то ошибка остается та же, но с другим именем.

2022-11-07 11:25 UTC, Farkhadov95 commented on js/popup.js
> +    hidePopup();
Все, уже сообразил)

2022-11-07 12:12 UTC, Farkhadov95 commented on js/popup.js
> +  comment.querySelector('.social__text').textContent = message;
точно)

2022-11-08 10:21 UTC, babtshe commented on js/popup.js
> +    hidePopup();
такие вопросы лучше в телегу писать, я читаю комменты на гитхабе обычно только при проверке домашки

2022-11-08 10:25 UTC, babtshe approved these changes

2022-11-08 10:25 UTC, babtshe commented on js/popup.js
> +   `<img class="social__picture" src="${avatar}" alt="${name}" width="35" height="35"><p class="social__text">${message}</p>`;
Почти всё хорошо, только для текста сообщения стоит помнить о [критерии](https://up.htmlacademy.ru/javascript/27/criteries#b27)

2022-11-08 10:25 UTC, merged