HW 8.22
htmlacademy-javascript/853355-kekstagram-27 pull request #8
Opened 2022-11-17 18:27 UTC by Farkhadov95

2022-11-17 18:33 UTC, Farkhadov95 commented
Добрый день/вечер!

Вроде все работает, но периодически выскакивает ошибка при отрисовке комментариев из за For Loop. Не знаю как это можно исправить. Что можно с этим сделать?

2022-11-18 07:27 UTC, babtshe requested changes

2022-11-18 07:27 UTC, babtshe commented on js/big-picture.js
> +    if (comments.childNodes.length < 5 || comments.childNodes.length === visibleCommentsCount) {
магию хорошо бы вынести в константы

2022-11-18 07:27 UTC, babtshe commented on js/big-picture.js
> +  };
По тз необходимо добавлять комменты при необходимости, а не все сразу с отменой скрытия.

2022-11-18 07:27 UTC, babtshe commented on js/big-picture.js
> +  const checkLoader = () => {
из названия функции совсем непонятно что она делает. Хорошо бы переименовать её так, чтобы не требовалось смотреть в её код для понимания последствий выполнения.

2022-11-18 07:27 UTC, babtshe commented on js/big-picture.js
> +    visibleCommentsCount += 5;
❗️

2022-11-24 08:25 UTC, babtshe approved these changes

2022-11-24 08:25 UTC, babtshe commented on js/big-picture.js
> +  let currentCommentsCount = COMMENT_COUNT * commetMultiplier;
опечатки в названиях переменных хорошо бы поправить здесь и далее по коду

2022-11-24 08:25 UTC, babtshe commented on js/big-picture.js
> +  if (currentCommentsCount > allCommentsArray.length || currentCommentsCount === allCommentsArray.length) {
больше или равно можно проверить так: `>=`

2022-11-24 08:25 UTC, merged